services:
  web:
    build: .
    ports:
      - "5002:8000"
    env_file:
      - .env
    depends_on:
      - product_hub_postgres

  product_hub_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: product_hub_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_hub_db
    ports:
      - "5435:5432"
    volumes:
      - product_hub_postgres:/var/lib/postgresql/data

volumes:
    product_hub_postgres:
