"""Initial migration.

Revision ID: 7dbe32a5002b
Revises: 
Create Date: 2024-07-02 22:32:17.388981

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7dbe32a5002b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False, autoincrement=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('length', sa.Float(), nullable=False),
                    sa.Column('width', sa.Float(), nullable=False),
                    sa.Column('height', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
